### ISSUE TITLE
[Question] Release tags

### ISSUE THREAD

**Issue by petrisorciprian-vitals** [screenshotbot/screenshotbot-oss#35]
I'm building the recorder script for ARM64 architecture, and am using the ```main``` branch at the moment for this.

Are there any plans for tagging of releases?

As I see, there are changes happening to main all the time which may potentially break builds.  
It would be helpful to have version release tags, or at least a 'stable' or 'latest' tag to make sure I'm not using broken binaries and am building to the same version or release.

Alternatively I can rely on a 'known working' commit sha, but would like to avoid this if possible.

**Comment by tdrhq** [comment]
There are two versions involved here, there's the version for the recorder script, and there's a version for the actual server.

The actual server is not versioned, we deploy nearly every commit. We do plan to version it over the next few months to support some on-premise installations.

The recorder is certainly versioned, but we wanted to avoid tagging it since it might be confused with the version for the actual server. A quick hack is look at the blame for this line: https://github.com/screenshotbot/screenshotbot-oss/blame/main/src/screenshotbot/sdk/screenshotbot.sdk.asd#L10, and use that commit to build the recorder.

**Comment by petrisorciprian-vitals** [comment]
I've implemented this solution, thanks!
